#!/usr/bin/env bash
# Run wichy in a Docker container with the current directory mounted

docker run -it --rm \
  -e WICHY_SKIP_HUMAN_VERIFICATION="True" \
  -p "${WICHY_HOST_PORT:-7899}":7891 \
  --add-host=host.docker.internal:host-gateway \
  wichy-test \
  "$@"
