"""
Patch tool for wichy - applies unified diff patches to files.
Uses the `patch_ng` library (patch-ng) for proper diff application.
"""

import os
import tempfile
from typing import Dict, List, Optional

try:
    from patch_ng import fromstring
except ImportError:
    fromstring = None

from pydantic import BaseModel, Field

from wichy.helpers.string import truncate_to_len
from wichy.tools.base import BaseTool, ParametersModel


class PatchParameters(ParametersModel):
    patch_content: str = Field(
        ...,
        description="unified diff patch content (output from diff -u or git diff)",
    )
    dry_run: bool = Field(
        False,
        description="if True, validate and show what would be changed without actually applying",
    )
    restrict_to_cwd: bool = Field(
        True,
        description="if True, restrict file operations to the current working directory (CWD)",
    )
    strip: int = Field(
        0,
        description="number of leading directories to strip from file paths (like patch -p). Default is 0.",
    )

    def info(self):
        summary = f"apply patch"
        if self.dry_run:
            summary += " (dry-run)"
        return summary


class PatchResult:
    """Result of patch application"""

    def __init__(self):
        self.applied_files: List[str] = []
        self.failed_files: List[str] = []
        self.skipped: List[str] = []
        self.errors: List[str] = []

    def success(self) -> bool:
        return len(self.errors) == 0 and len(self.failed_files) == 0

    def summary(self) -> str:
        lines = []
        if self.applied_files:
            lines.append(f"Applied: {len(self.applied_files)} file(s)")
            for f in self.applied_files[:5]:
                lines.append(f"  ✓ {f}")
            if len(self.applied_files) > 5:
                lines.append(f"  ... and {len(self.applied_files)-5} more")
        if self.failed_files:
            lines.append(f"Failed: {len(self.failed_files)} file(s)")
            for f in self.failed_files[:5]:
                lines.append(f"  ✗ {f}")
            if len(self.failed_files) > 5:
                lines.append(f"  ... and {len(self.failed_files)-5} more")
        if self.errors:
            lines.append(f"Errors: {len(self.errors)}")
            for e in self.errors[:5]:
                lines.append(f"  ! {truncate_to_len(e, 100)}")
            if len(self.errors) > 5:
                lines.append(f"  ... and {len(self.errors)-5} more")
        if self.skipped:
            lines.append(f"Skipped: {len(self.skipped)} file(s)")

        if not lines:
            return "No changes made"

        return "\n".join(lines)


class PatchTool(BaseTool):
    name = "patch"
    description = "Apply unified diff patches to files."
    description_long = """
Applies unified diff patches (as generated by `diff -u` or `git diff`) to files in the workspace.
This tool uses the `patch_ng` library to correctly handle context lines, additions, and deletions.

Important parameters:
- `restrict_to_cwd`: Safety boundary - when True (default), all target files must be within the current working directory
- `strip`: Number of leading directories to strip from file paths (use -p1 etc). Default 0.
- `dry_run`: Validate without applying, showing what would change

The patch content must be in standard unified diff format with --- and +++ headers and @@ hunk markers.
"""
    parameters_model = PatchParameters

    def execute(
        self,
        patch_content: str,
        dry_run: bool = False,
        restrict_to_cwd: bool = True,
        strip: int = 0,
    ) -> str:
        """Execute patch application using the patch_ng library"""
        result = PatchResult()

        # Check if patch library is available
        if fromstring is None:
            return "error: patch_ng library not installed. Install with: pip install patch-ng"

        try:
            # Parse the patch - patch_ng expects bytes
            try:
                patch_set = fromstring(patch_content.encode('utf-8'))
                if patch_set is False:
                    return "error: failed to parse patch - invalid unified diff format"
            except Exception as e:
                return f"error: failed to parse patch: {e}"

            # Collect affected files (target names are bytes, decode them)
            affected_files: List[str] = []
            for p in patch_set:
                # p.target is bytes like b'b/test.txt', decode to string
                target_file = p.target.decode('utf-8', errors='replace')
                affected_files.append(target_file)

            if not affected_files:
                return "error: patch contains no file changes"

            # Validate all target files are within allowed boundaries
            if restrict_to_cwd:
                cwd = os.getcwd()
                for file_path in affected_files:
                    abs_file = os.path.abspath(os.path.join(".", file_path))
                    if not abs_file.startswith(cwd):
                        result.errors.append(f"'{file_path}' is outside the workspace")
                        result.failed_files.append(file_path)
                if result.errors:
                    return "error: patch validation failed:\n" + result.summary()

            # If dry run, just report what would be applied
            if dry_run:
                result.applied_files = affected_files
                header = "DRY RUN - would apply patch to:\n"
                return header + result.summary()

            # Apply the patch
            success = patch_set.apply(strip=strip, root=None)
            
            if success:
                result.applied_files = affected_files
                return result.summary()
            else:
                for p in patch_set:
                    target_file = p.target.decode('utf-8', errors='replace')
                    result.failed_files.append(target_file)
                result.errors.append("Patch application failed")
                return "error: patch application incomplete with errors:\n" + result.summary()

        except Exception as e:
            return f"error: {e}"
