from .agent_desc_code_reviewer import agent_code_reviewer
from .agent_desc_web_researcher import agent_web_researcher, agent_web_researcher_lite
from .agent_desc_code_planner import agent_code_planner
from .agent_desc_code_implementer import agent_code_implementer
from .sub_agent import new_sub_agent_as_tool

code_reviewer_agent = new_sub_agent_as_tool(markdown_description=agent_code_reviewer)
code_planner_agent = new_sub_agent_as_tool(markdown_description=agent_code_planner)
code_implementer_agent = new_sub_agent_as_tool(markdown_description=agent_code_implementer)
web_research_agent = new_sub_agent_as_tool(markdown_description=agent_web_researcher)
web_research_agent_lite = new_sub_agent_as_tool(markdown_description=agent_web_researcher_lite)