from .agent_desc_code_reviewer import agent_code_reviewer
from .agent_desc_web_researcher import agent_web_researcher, agent_web_researcher_lite
from .sub_agent import new_sub_agent_as_tool

code_agent = new_sub_agent_as_tool(markdown_description=agent_code_reviewer)
web_research_agent = new_sub_agent_as_tool(markdown_description=agent_web_researcher)
web_research_agent_lite = new_sub_agent_as_tool(markdown_description=agent_web_researcher_lite)